Further remove autoloading, the issue still repros on jruby and truffle
Repro:

    require 'http/cookie'

    # We only care about the first exception, not all of them
    Thread.report_on_exception = false

    100.times.map do
      Thread.new do
        HTTP::CookieJar::HashStore.new
      end
    end.each(&:join)

The above will reliably trigger an exception on all versions of
TruffleRuby and many versions of JRuby.  For example:

        $ ruby -v
        truffleruby 22.3.1, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]
        $ ruby repro.rb
        /home/cbrasic/repos/http-cookie/lib/http/cookie_jar/abstract_store.rb:50:in `initialize': undefined method `each_pair' for nil:NilClass (NoMethodError)
                from repro.rb:10:in `block (2 levels) in <main>'

        $ jruby --version
        jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.372-b07 on 1.8.0_372-b07 +jit [linux-x86_64]
        $ jruby repro.rb
        NameError: can't resolve constant HashStore after loading http/cookie_jar/hash_store
              const_missing at /home/cbrasic/.asdf/installs/ruby/jruby-9.1.2.0/lib/ruby/gems/shared/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:25
          block in repro.rb at repro.rb:10